# Generated by Django 2.2.6 on 2019-10-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20191008_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='debate.Post', verbose_name='Topic'),
            preserve_default=False,
        ),
    ]
